config/routes.rb
Rails.application.routes.draw do
  get  'microposts/index'
  post 'microposts/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  mount_uploader :picture, PictureUploader

  validates :picture, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def index
    @microposts = Micropost.all
  end

  def create
    if params[:micropost]
      @micropost = Micropost.new(picture: params[:micropost][:picture])
      if @micropost.save
        flash[:success] = "Micropost created success!"
      else
        flash[:notice] = "Micropost created failure..."
      end
    end
    redirect_to microposts_index_url
  end

  private

    def micropost_params
      params.require(:micropost).permit(:picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ImageUploadTest
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/microposts/index.html.slim
h1 Microposts#index
p Find me in app/views/microposts/index.html.slim

ul
  - flash.each do |msg_type,msg|
    li
      = msg

- @microposts.each do |micropost|
  = image_tag micropost.picture.url if micropost.picture?

/ f.file_fieldをフォームヘルパー使わず出力する場合は、
/ form_withのオプションで、mulitipart: true をつけないと
/ ファイルアップロードできないので注意。
= form_with model: Micropost.new, url: microposts_create_path do |f|
  = f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'
  = f.submit